### ISSUE TITLE
collapsed class in bs_collapse.php in function bs_citem()

### ISSUE THREAD

**Issue by grandgeorg** [TheWebShop/bootstrap-shortcodes#43]
Please consider adding "collapsed" css class to toggle link in bs_collapse.php in function bs_citem() line: 26. The line would then be:
```php
$result .= '<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#' . $parent . '" href="#' . $id . '">';
```
This is important so one can add css styles to collapsed and non-collapsed items like so for example:
```css
    a.collapsed:before{
        content:"\2b";
        font-family:"Glyphicons Halflings";
        display:inline-block;
    }
    a:before{
        content:"\2212";
        font-family:"Glyphicons Halflings";
        display:inline-block;
    }
```
Otherwise JS is adding collapsed class __only after__ first expand action.
Also consider adding aria-attributes to the panels, like in the example from bootstrap:

http://getbootstrap.com/javascript/#collapse-examples

The lines 24 to 31 then would be:
```php
    $result .= '    <div class="panel-heading" role="tab" id="heading_' . $id . '">';
    $result .= '        <h4 class="panel-title">';
    $result .= '<a class="accordion-toggle collapsed" data-toggle="collapse" aria-expanded="true" aria-controls="heading_' . $id . '" data-parent="#' . $parent . '" href="#' . $id . '">';
    $result .= $title;
    $result .= '</a>';
    $result .= '        </h4>';
    $result .= '    </div>';
    $result .= '    <div id="' . $id . '" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_' . $id . '">';
```
